### PR TITLE
buffer support moved to optional parameter `supportBufffer`

### PR DESCRIPTION
**Pull request by glebmachine**
- `supportBuffer` now optional, with default `false`
 - cleanup some jshint warnings
 - demo image results added to .gitignore
 - test also included

### CODE REVIEW

**Comment by Turbo87** [comment]
@stefanpenner could you review and merge this to (hopefully) resolve https://github.com/TryGhost/Ghost/issues/6953?

**Comment by stefanpenner** [comment]
ci failed

**Comment by stefanpenner** [comment]
also worth noting, the issue in ghost is only a warning. It still works

**Comment by glebmachine** [comment]
Yeah.. 
Check it soon (about 1/2 hours)

Thank you)

**Comment by stefanpenner** [comment]
@glebmachine looks like that is merely an appveyor issue, not an issue with your code.

**Comment by glebmachine** [comment]
Y, looks like)

**Comment by stefanpenner** [comment]
fixing here: https://github.com/stefanpenner/async-disk-cache/pull/19

**Pull request merged**
