### PR TITLE
[Fixes #66, #63] Reads could encounter partially completed writes.

### LINKED ISSUE #66: Race condition when sharing cache
If the persistent cache is being accessed by more than one process, it's possible to see partially-written records in the cache.

Instead we could write each new file to a globally unique temporary name and then atomically rename it to the real shared name.

Same issue on the sync sibling of this library: https://github.com/stefanpenner/sync-disk-cache/issues/18

### PR DESCRIPTION
**Pull request by stefanpenner**
[Fixes #66, #63] Reads could encounter partially completed writes.

Approach:

* write files to a random tmp file
* once complete, use renameFile to atomically move the tmp file to the
  expected outputFile

Performance impact:

In general, at-least when being used as part of broccoli's build system,
this library is most sensitive to read performance and this approach
makes no changes to that flow. As for the right flow, testing suggests
file rename to be relatively small overhead relative to actually writing
the file.

Future work:

* when in same process: reads may want to wait for corresponding writes to
  finish before reading.
* we may want to partition files further to prevent single directories
  with a huge number of contained files.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Test failure is related to an unsupported version of node, and our dependency installation tool not supporting it.

Once this lands, we will follow up with a major bump that explicitly drops support for unsupported nodes. But at this time, we would like this fix to land where possible, and a major bump would slow adoption.

**Comment by chancancode** [comment]
We just ran into the problem this PR supposedly fixes:

```
=================================================================================

ENV Summary:

  TIME: Thu Feb 06 2020 14:39:20 GMT-0800 (Pacific Standard Time)
  TITLE: ember
  ARGV:
  - /Users/pairing/.volta/tools/image/node/10.16.3/6.9.0/bin/node
  - /Code/glimmer/node_modules/.bin/ember
  - s
  - -p
  - 4201
  EXEC_PATH: /Users/pairing/.volta/tools/image/node/10.16.3/6.9.0/bin/node
  TMPDIR: /var/folders/_7/8wwzqn8j1wlc91y9kgm_mq580000gp/T
  SHELL: /bin/zsh
  PATH:
  - /Users/pairing/.volta/tools/image/node/10.16.3/6.9.0/bin
  - /Users/pairing/.volta/tools/image/yarn/1.17.3/bin
  - /Users/pairing/.rvm/gems/ruby-2.6.2/bin
  - /Users/pairing/.rvm/gems/ruby-2.6.2@global/bin
  - /Users/pairing/.rvm/rubies/ruby-2.6.2/bin
  - /Users/pairing/.yarn/bin
  - /Users/pairing/.config/yarn/global/node_modules/.bin
  - /Users/pairing/.cargo/bin
  - /Users/pairing/.cargo/bin
  - /usr/local/bin
  - /usr/local/sbin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /opt/X11/bin
  - /Applications/Postgres.app/Contents/Versions/latest/bin
  - /Users/pairing/.rvm/gems/ruby-2.6.2/bin
  - /Users/pairing/.rvm/gems/ruby-2.6.2@global/bin
  - /Users/pairing/.rvm/rubies/ruby-2.6.2/bin
  - /Users/pairing/.yarn/bin
  - /Users/pairing/.config/yarn/global/node_modules/.bin
  - /Users/pairing/.cargo/bin
  - /Users/pairing/.rvm/bin
  - /anaconda/bin
  - /Code/direwolf-ops/bin
  - /Users/pairing/.rvm/bin
  - /anaconda/bin
  - /Code/direwolf-ops/bin
  PLATFORM: darwin x64
  FREEMEM: 259846144
  TOTALMEM: 34359738368
  UPTIME: 271222
  LOADAVG: 4.1845703125,4.31298828125,4.33203125
  CPUS:
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 4000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 4
  - nghttp2: 1.39.2
  - node: 10.16.3
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
  - code: [undefined]
  - codeFrame: unexpected end of file
  - errorMessage: @glimmer/runtime/lib/vm/attributes/index.js: unexpected end of file
        in /var/folders/_7/8wwzqn8j1wlc91y9kgm_mq580000gp/T/broccoli-44725trmKRSxwONPv/out-196-funnel
        at broccoli-persistent-filter:Babel > [Transpile CommonJS - @glimmer/runtime - es5] (Transpile CommonJS - @glimmer/runtime - es5)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: @glimmer/runtime/lib/vm/attributes/index.js
    - line: [undefined]
    - treeDir: /var/folders/_7/8wwzqn8j1wlc91y9kgm_mq580000gp/T/broccoli-44725trmKRSxwONPv/out-196-funnel
  - message: @glimmer/runtime/lib/vm/attributes/index.js: unexpected end of file
        in /var/folders/_7/8wwzqn8j1wlc91y9kgm_mq580000gp/T/broccoli-44725trmKRSxwONPv/out-196-funnel
        at broccoli-persistent-filter:Babel > [Transpile CommonJS - @glimmer/runtime - es5] (Transpile CommonJS - @glimmer/runtime - es5)
  - name: BuildError
  - nodeAnnotation: Transpile CommonJS - @glimmer/runtime - es5
  - nodeName: broccoli-persistent-filter:Babel > [Transpile CommonJS - @glimmer/runtime - es5]
  - originalErrorMessage: unexpected end of file
  - stack: Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)

=================================================================================
```

After backing the cache directory, we removed it and the build with a fresh cache directory worked. We restored the cache directory again, and the same error came back. We then inspected the corrupted cache folder and found two zero-sized files. Deleting the two zero-sized files (while keeping the rest of the original cache directory) also fixes the problem.

**Comment by chancancode** [comment]
Some people on the Internet seems to suggest that renaming is not always atomic (in OS X)? In any case, it seems like this error can be avoided by treating corrupted entries as if they don't exist?

**Comment by stefanpenner** [comment]
@chancancode can you run `yarn why async-disk-cache` and `yarn why sync-disk-cache` I want to know what versions you are using.

**Comment by chancancode** [comment]
Ahhh good call. My bad, should have checked. (This is https://github.com/glimmerjs/glimmer-vm by the way.)

```
~/C/glimmer ❯❯❯ yarn why async-disk-cache
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "async-disk-cache"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "async-disk-cache@1.3.3"
info Reasons this module exists
   - "_project_#broccoli-persistent-filter" depends on it
   - Hoisted from "_project_#broccoli-persistent-filter#async-disk-cache"
   - Hoisted from "_project_#emberjs-build#broccoli-persistent-filter#async-disk-cache"
   - Hoisted from "_project_#broccoli-stew#broccoli-persistent-filter#async-disk-cache"
   - Hoisted from "_project_#broccoli-babel-transpiler#broccoli-persistent-filter#async-disk-cache"
   - Hoisted from "_project_#emberjs-build#broccoli-lint-eslint#broccoli-persistent-filter#async-disk-cache"
   - Hoisted from "_project_#emberjs-build#broccoli-string-replace#broccoli-persistent-filter#async-disk-cache"
   - Hoisted from "_project_#ember-cli#ember-cli-preprocess-registry#broccoli-clean-css#broccoli-persistent-filter#async-disk-cache"
info Disk size without dependencies: "44KB"
info Disk size with unique dependencies: "2.34MB"
info Disk size with transitive dependencies: "2.86MB"
info Number of shared dependencies: 18
✨  Done in 0.79s.
~/C/glimmer ❯❯❯ yarn why sync-disk-cache
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "sync-disk-cache"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.68s.
```

**Comment by stefanpenner** [comment]
@chancancode the fix is only available in `v2.0.0` and  `v1.3.5`. It appears you are using `1.3.3`, which can still hit this bug.

As for OSX rename not always being atomic, if memory serves old versions of OSX did have some serious issues here, but I believe they have been resolved. It's possible other issues exist... I will gladly investigate further if once you upgrade the issues still arise.

**Comment by chancancode** [comment]
@stefanpenner yes, totally my bad, sorry for the noise: I have a PR to upgrade: https://github.com/glimmerjs/glimmer-vm/pull/1026

**Comment by stefanpenner** [comment]
> @stefanpenner yes, totally my bad

@chancancode not a problem

**Comment by stefanpenner** [comment]
> In any case, it seems like this error can be avoided by treating corrupted entries as if they don't exist?

@chancancode In regards to having a `get` behave as if there was a `CacheEntry.MISS`, if the file appeared to be corrupted, something like the following could work:

```js
catch (e) {
  if (isZlibError(e)) {
    try {
     unlink.sync(CORRUPTED_FILE_PATH);
    } catch (e) {
      if (isENOENT(e)) {  }
      else { throw e;}
    } 
  } else {
    throw e;
  }
}
```

Pro:

* hide/absorb any corruption issues if the cache is compressed

Con:

* with #67 in place, the chance of this occurring and not being a legit bug worth surfacing is pretty low.

**Comment by stefanpenner** [comment]
Thinking about it more, although we can gracefully ignore corrupted cache results, when they corrupt something seriously must have gone wrong. I wonder if we should simply error but with something more actionable, like: Your cache appears to have been corrupted please run xyz to purge the cache, if the problem persists please report this via https://github.com/stefanpenner/async-disk-cache/issues/new

**Comment by stefanpenner** [comment]
Ya, I'm pretty sure hiding cache corruption will more then likely result in real issues becoming hidden. I would like to leave things as they are today, if post #67 problems arise we can re-evaluate.

**Pull request merged**
