### PR TITLE
Buffer bug resolved

### PR DESCRIPTION
**Pull request by glebmachine**
https://github.com/stefanpenner/async-disk-cache/issues/16

### CODE REVIEW

**Comment by glebmachine** [comment]
Tests are included for sure)

**Comment by stefanpenner** [comment]
thanks

**Comment by stefanpenner** [comment]
```
➜  async-disk-cache git:(master) git tag v1.0.4
➜  async-disk-cache git:(master) git push origin v1.0.4
npm publish
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:stefanpenner/async-disk-cache.git
 * [new tag]         v1.0.4 -> v1.0.4
➜  async-disk-cache git:(master) npm publish
+ async-disk-cache@1.0.4
```

**Comment by glebmachine** [comment]
ty)

**Comment by stefanpenner** [comment]
I believe this is causing a performance regression

**Comment by glebmachine** [comment]
May be a little, but without this you can't work with files.

May be, better to add this feature as optional parameter, like 'supportBuffer' default 'false'?

**Comment by stefanpenner** [comment]
> May be, better to add this feature as optional parameter, like 'supportBuffer' default 'false'?

👍 are you able to submit a PR for this (im currently swamped)

**Comment by glebmachine** [comment]
Yes, sure.

I will implement this tomorrow (Friday, 3), ok?

**Comment by stefanpenner** [comment]
@glebmachine sound wonderful :)

**Comment by glebmachine** [comment]
Done)
https://github.com/stefanpenner/async-disk-cache/pull/18

**Comment by Turbo87** [comment]
this unfortunately has caused https://github.com/TryGhost/Ghost/issues/6953 since `istextorbinary` doesn't seem to be compatible with Node 0.10

**Comment by Turbo87** [comment]
OTOH this project is tested against Node 0.10 so this might need further investigation

**Comment by glebmachine** [comment]
Yep, got it.
You have to merge this PR https://github.com/stefanpenner/async-disk-cache/pull/18

At this pull request istextorbinary usage become optional (only for guys, who want to deal with buffers, not for everybody)

**Comment by Turbo87** [comment]
@glebmachine cool, thanks for the fast feedback

**Comment by glebmachine** [comment]
@Turbo87 you are welcome)

**Pull request merged**
